POST http://localhost:5000/users/register
Content-Type: application/json

{
    "username": "ville",
    "password": "salasana"
}

###

DELETE http://localhost:5000/users/ville

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username": "ville",
    "password": "salasana"
}

###

GET http://localhost:5000/users/

###

PATCH http://localhost:5000/users/ville
Content-Type: application/json

{
    "username": "ville",
    "password": "123",
    "newPassword": "salasana"
}

###########################################################


POST http://localhost:5000/memes/delete/46d1a2231d616716.jpg
Content-Type: application/json

{
    "username": "ville",
    "token": "5deaa0b10bc8b917ab06840bdb660a79abca98347fc27470185413b7a5723b7f"
}

###

GET http://localhost:5000/memes/file/b85f515b17c61c4c.jpg

###

GET http://localhost:5000/memes/random

###

POST http://localhost:5000/memes/user/ville
Content-Type: application/json

{
    "username": "ville",
    "token": "5deaa0b10bc8b917ab06840bdb660a79abca98347fc27470185413b7a5723b7f"
}