POST http://localhost:5000/users/register
Content-Type: application/json

{
    "username": "ville",
    "password": "salasana"
}

###

DELETE http://localhost:5000/users/ville

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username": "ville",
    "password": "salasana"
}

###

GET http://localhost:5000/users/


###########################################################


GET http://localhost:5000/memes/

###

DELETE http://localhost:5000/memes/deleteall

###

GET http://localhost:5000/memes/file/b85f515b17c61c4c.jpg

###

GET http://localhost:5000/memes/random